version: "3"

services:
  base:
    image: mobile-robots-project
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    stdin_open: true
    # tty: true
    network_mode: host
    ipc: host
    privileged: true
    command: ros2 run ariaNode ariaNode