version: "3"

services:
  base:
    image: mobile-robots-project
    build:
      # context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # stdin_open: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 189:* rmw'
    # tty: true
    network_mode: host
    # ipc: host
    # privileged: true
    command: ros2 run ariaNode ariaNode && ros2 topic pub /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}"