version: "3"

services:
  base:
    image: mobile-robots-project
    build:
      # context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # stdin_open: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 189:* rmw'
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    # command: /bin/bash -c "source ./install/setup.bash" && ros2 run ariaPackage ariaPackage -rp /dev/ttyUSB0
    command: ros2 launch master_package main.launch.py
    # command: ros2 launch master_package main.launch.py
    # command: /bin/bash -c "source ./install/setup.bash" && ros2 run ariaNode ariaNode -rp /dev/ttyUSB0 && ros2 interface show geometry_msgs/msg/Twist
    # command: ros2 run ariaNode ariaNode && ros2 topic pub /cmd_vel geometry_msgs/msg/Twist "{linear: {x: 0.5, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}"
  controller:
    image: mobile-robots-project
    build: .
    volumes:
      - type: bind
        source: /dev
        target: /dev
    depends_on:
    - base
    device_cgroup_rules:
      - 'c *:* rmw'
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    # command: ros2 run joy joyNode && ros2 launch teleop_twist_joy teleop-launch.py
    command: ros2 run ariaNode ariaNode -rp /dev/ttyUSB0
  camera:
    image: mobile-robots-project
    build: .
    depends_on:
    - base
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
    device_cgroup_rules:
      - 'c *:* rmw'
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    command: ros2 launch depthai_ros_driver camera.launch.py
  # rviz:
  #     image: ros-rviz
  #     command: rviz
  #     depends_on:
  #       - base
  #     runtime: nvidia
  #     environment:
  #       - DISPLAY=${DISPLAY}
  #       - "ROS_MASTER_URI=http://roscore:11311"
  #       - NVIDIA_VISIBLE_DEVICES=all
  #       - NVIDIA_DRIVER_CAPABILITIES=all
  #       - QT_X11_NO_MITSHM=1 # Fix a bug with QT
  #     user: ${UID}
  #     volumes:
  #       - ${HOME}/.Xauthority:/root/.Xauthority:rw
  #       - /tmp/.X11-unix:/tmp/.X11-unix
  #       - /etc/group:/etc/group:ro
  #       - /etc/passwd:/etc/passwd:ro
  #       - /etc/shadow:/etc/shadow:ro
  #       - /etc/sudoers:/etc/sudoers:ro
  #       - /etc/sudoers.d:/etc/sudoers.d:ro
  #       - /home/${USER}:/home/${USER}:rw #share your home with write permissions
  #     privileged: true
      # networks:
      #   - ros-network