version: "3"

services:
  base:
    image: mobile-robots-project:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c *:* rmw'
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    command: ros2 launch master_package main.launch.py

  controller:
    image: mobile-robots-project
    build: .
    volumes:
      - type: bind
        source: /dev
        target: /dev
    depends_on:
      - base
    device_cgroup_rules:
      - 'c *:* rmw'
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    command: ros2 run ariaNode ariaNode -rp /dev/ttyUSB0

  camera:
    image: mobile-robots-project:latest
    build: .
    depends_on:
      - base
    volumes:
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
    device_cgroup_rules:
      - 'c *:* rmw'
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    command: ros2 launch depthai_ros_driver camera.launch.py

  rviz:
    image: mobile-robots-project:latest
    network_mode: host
    command: ros2 launch master_package rviz.launch.py
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - type: bind
        source: /dev/shm
        target: /dev/shm

  m-explore-ros2:
    image: mobile-robots-project:latest
    build: .
    depends_on:
      - base
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c *:* rmw'
    environment:
      - ROS_DOMAIN_ID=153
      - ROS_MASTER_URI=http://localhost:11311
    command: ros2 launch explore_lite explore.launch.py
