version: "3"

services:
  base:
    image: mobile-robots-project:latest
    build:
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    #   target: base
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 189:* rmw'
    network_mode: host
    # command: ros2 pkg prefix ariaPackage --share
    # command: ros2 node list
    command: ros2 run ariaPackage ariaPackage -rp /dev/ttyUSB0
  # camera:
  #   image: mobile-robots-project
  #   build:
  #     dockerfile: Dockerfile
  #     args: 
  #       ROS_DISTRO: humble
  #     target: base
  #   command: python3 cam_connect.py -rp /dev/ttyUSB1 #change this later

