version: "3"

services:
  base:
    image: mobile-robots-project
    build:
      # context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # stdin_open: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
    device_cgroup_rules:
      - 'c 188:* rmw'
      - 'c 189:* rmw'
    # tty: true
    network_mode: host
    # ipc: host
    # privileged: true
    # command: /bin/bash -c "source ./install/setup.bash" && ros2 run ariaPackage ariaPackage -rp /dev/ttyUSB0
    command: ros2 run ariaNode ariaNode -rp /dev/ttyUSB0
    # command: /bin/bash -c "source ./install/setup.bash" && ros2 run ariaNode ariaNode -rp /dev/ttyUSB0 && ros2 interface show geometry_msgs/msg/Twist